import { Box, Container, useColorModeValue } from "@chakra-ui/react";
import Head from "next/head";
import React, { ReactNode } from "react";
import Header from "./Header";

interface LayoutProps {
  children: ReactNode;
}

const Layout = ({ children }: LayoutProps) => {
  const bgColor = useColorModeValue("lightOne", "darkOne");

  return (
    <Box w="full" minHeight="100vh" h="full" bg={bgColor}>
      <Container h="full" maxW="container.lg" py="4" px={[6, null]}>
        <Head>
          <title>LagStats</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <Header />

        {children}
      </Container>
    </Box>
  );
};

export default Layout;
